### ISSUE TITLE
Is jellyfish.pdf up to date?

### ISSUE THREAD

**Issue by mmokrejs** [gmarcais/Jellyfish#123]
Hi,
  I was just looking at the differences between jellyfish-2.2.9/doc/jellyfish.pdf (v1.1.4) and ftp://ftp.genome.umd.edu/pub/jellyfish/JellyfishUserGuide.pdf . OK, the former seems longer and hence probably newer. But, jellyfish1 and jellyfish2 differ in their commandline syntax. So is the 1.1.4 pdf file really matching jellyfish-2.2.9?

**Comment by gmarcais** [comment]
The 1.1.4 pdf has not been updated in a while for sure, but it matches version 2 rather than 1.

Now, I recently transformed the content of the PDF to a mark down formatted documentation and directly [visible in Github](https://github.com/gmarcais/Jellyfish/tree/master/doc). This will become the master document.
