### ISSUE TITLE
Compile error on 2.3.0

### ISSUE THREAD

**Issue by sjaenick** [gmarcais/Jellyfish#159]
Hi there, 

attempting to build Jellyfish 2.3.0 from source on Ubuntu 16.04 LTS, build fails:

```
$ autoreconf -vif
$ ./configure
[output omitted]
$ make
make: *** No rule to make target 'false', needed by 'sub_commands/count_main_cmdline.hpp'.  Stop.
```

Any hints?

**Comment by gmarcais** [comment]
You should download the source release tarball [jellyfish-2.3.0.tar.gz](https://github.com/gmarcais/Jellyfish/releases/download/v2.3.0/jellyfish-2.3.0.tar.gz) and compile from that. You don't need to run `autoreconf`, only `./configure && make && make install`.

I you install from the Github development tree instead of the release tar ball, then you need to have `yaggo` in your path.

This is explained in the [Installation](https://github.com/gmarcais/Jellyfish#installation) instructions.

**Comment by guerreromanuel** [comment]
This problem still happens if you do "make distclean" and then try to configure and make again.
