### ISSUE TITLE
Example compile error

### ISSUE THREAD

**Issue by gonzalogacc** [gmarcais/Jellyfish#33]
Hi, i'm trying to compile the examples, and i keep getting this error from the compiler

In file included from query_per_sequence.cc:22:
include/jellyfish-2.2.0/jellyfish/stream_manager.hpp:98:12: error: calling a private constructor of class 'std::__1::unique_ptr<std::__1::basic_istream<char>,
      std::__1::default_delete<std::__1::basic_istream<char> > >'
    return res;
           ^
Does anybody have any idea what i'm missing!??
Thanks
Gonza.-

**Comment by gmarcais** [comment]
Can you give us some more information: what OS you are on, what compiler and version you are using?

Guillaume.

**Comment by gonzalogacc** [comment]
Sure, i' running MacOS yosemite  v10.10.3 and this  the compiler is:

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

Gonza.-

**Comment by gmarcais** [comment]
On some version of MacOS, the compiler is too old. We require at least version 4.4 of gcc (and the C++ standard library), and it ships with 4.2. You have to install a newer version of gcc, for example using macports. There is some information on the web page: http://www.genome.umd.edu/jellyfish.html

Another remark. This switch --prefix=/Applications/Xcode.app/Contents/Developer/usr tell where to install Jellyfish after compilation. I think you want to pass --prefix=$HOME (or some other place where you keep your manually compiled software) instead of installing in the Xcode app folder.

Guillaume.
