### ISSUE TITLE
RE: 2.1.2 is not buildable #11

### ISSUE THREAD

**Issue by nclaesnacw** [gmarcais/Jellyfish#43]
I am in awe of the providers of software.
Having said that, as a 'potential' biologist user "what a nightmare!"
I would love to try Jellyfish
I am using a mid-2009 MacBook Pro with El Capitan, Xcode CLI MacPorts ...
I've just updated everything (except the gcc, which is gcc5 experimental :-(  I don't seem to get it in CLI or MacPorts - g++ is in fink, I seem to have clang )
and followed stuff at issue #11 
to try and solve the No rule to make target `false' needed by `sub_commands/count_main_cmdline.hpp'
I downloaded the tar from the Jellyfish 2.0 web site (but it takes you to Git)
and it turns out that is where yaggo is used in the makefile

yaggo install
Quick and easy
To install the yaggo script into your home directory, do:
make DEST=$HOME/bin

I am now lost at gmarcais/yaggo I can't even see what to download and I have no idea whether it will work on the mac, and when I do, do I now have to install ruby ... it is never ending (and of course, for the next programme, completely different) - sorry for the moan :-(
Any help gratefully received
Thanks
Alan Ward

**Comment by gmarcais** [comment]
> I am in awe of the providers of software.

Thanks, glad I could help.

> Having said that, as a 'potential' biologist user "what a nightmare!"

Whoops. Sorry about that.

The link on the webpage should take you to the release page of github. You should compile from the release, not the cloned github tree (unless you plan on contributing to the Jellyfish code). Download the latest [tarball version 2 2 3](https://github.com/gmarcais/Jellyfish/releases/download/v2.2.3/jellyfish-2.2.3.tar.gz).

The release code does not depend on yaggo. Now this should work:

```
./configure --prefix $HOME
make -j 4
make install
```

If everything compiled and installed, then `~/bin/jellyfish --help` should display some help information. You can install somewhere else than in your home directory by passing another path to `--prefix`.

Now, Jellyfish is not as well tested on the Mac because Apple, by refusing to run OS X in virtual machines, makes it hard for me to test my software on their platform. But do report any bugs, I'll try to fix them.
