### ISSUE TITLE
Can't merge hash with different size

### ISSUE THREAD

**Issue by gusevfe** [gmarcais/Jellyfish#50]
Hi!

I am trying to merge two jellyfish databases, but it exits with this message:
``
Can't merge hash with different size (4294967296, 2147483648)
``
Is there any way to work it out?

I am using v2.2.4.

Thank you in advance.

**Comment by kes1smmn** [comment]
You can recount the two libraries using the same hash size with the -s flag.  (e.g -s 6G). Make sure you give it enough ram so jellyfish count does not automatically resize.

**Comment by gmarcais** [comment]
Adding to kes1smm answer, you can use the '--disk' switch to forbid Jellyfish from doing size doubling. This will guarantee you can merge the outputs, provided the '-s' flag was the same.

**Comment by gusevfe** [comment]
@gmarcais, @kes1smmn Thank you! Indeed, using these two switches fix the error.

**Comment by phil-grayson** [comment]
Could I suggest that a note about this be included in the "help" calls for count and/or merge?  Due to my compute architecture and file structure, it seemed like it would be better for me to parallelize the count calls (computationally intensive) across my libraries and merge afterwards (very cheap).  I tested this on a couple files and then ran it across my entire experiment.  After running count across 120 files fastq with between 36 and 80 Gb of memory requested per job, I need to completely start again because I can't merge my files.  That's a lot of wasted compute.
